# Remove default mappings to avoid conflicts
clear_all_shortcuts no

# Your Custom Mappings
map ctrl+a  paste_from_clipboard
map ctrl+z  copy_to_clipboard

# Keep Ctrl+C for interrupting processes (Standard Dev behavior)
# Keep Ctrl+V for other terminal needs if necessary
