exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
bind = SUPER, M, exec, hyprctl dispatch exit
bind = SUPER, N, exec, systemctl poweroff
exec-once = waybar
# --- FIXED HEADER ---
$mainMod = SUPER

exec-once = nm-applet --indicator
# THE BINDS (If these don't work, the file is broken below line 30)
bind = $mainMod, Q, exec, kitty
bind = $mainMod, X, killactive,
bind = $mainMod, SPACE, exec, wofi --show drun
bind = $mainMod, RETURN, exec, kitty

input {
    follow_mouse = 2
    float_switch_override_focus = 0
    kb_layout = us
    touchpad {
        tap-to-click = true
    }
}
# --- END FIXED HEADER ---
